clients show now working
agustinfranc/at-back pull request #24
Opened 2022-10-05 15:21 UTC by francocava

2022-10-05 15:24 UTC, agustinfranc requested changes
corregir nombre del pr, no es un fix.

ej; show client

2022-10-08 22:26 UTC, agustinfranc requested changes
el repo de get tiene que tener tambien los metodos que hiciste en el rpeo del show. los repo show no son necesarios. sino estaria mal el nombre del get.

2022-10-09 22:37 UTC, agustinfranc commented on app/Repositories/Companion/ShowCompanionRepository.php
> +}
no a los largos pr, este pr es de clientes. no tirar codigo de mas

2022-10-09 22:38 UTC, agustinfranc commented on app/Repositories/Assignment/ShowAssignmentRepository.php
> +}
no a los largos pr, este pr es de clientes. no tirar codigo de mas

2022-10-09 22:38 UTC, agustinfranc commented on app/Http/Controllers/CompanionController.php
>  use App\Http\Requests\Companion\UpdateCompanionRequest;
no a los largos pr, este pr es de clientes. no tirar codigo de mas

2022-10-09 22:38 UTC, agustinfranc commented on app/Http/Controllers/AssignmentController.php
>  use App\Http\Requests\Assignment\UpdateAssignmentRequest;
no a los largos pr, este pr es de clientes. no tirar codigo de mas

2022-10-10 23:35 UTC, francocava commented on app/Http/Controllers/AssignmentController.php
>  use App\Http\Requests\Assignment\UpdateAssignmentRequest;
Tenes razón, me cebe y hice los show de las demás cosas. Tendrian que haber sido 3 prs. Ahí cambie el titulo

2022-10-11 12:43 UTC, agustinfranc requested changes
deshacer cambios en assignment controller

2022-10-11 12:43 UTC, agustinfranc commented on app/Http/Controllers/AssignmentController.php
> +use App\Repositories\Assignment\ShowAssignmentRepository;
no va

2022-10-11 12:43 UTC, agustinfranc commented on app/Http/Controllers/AssignmentController.php
> +        private readonly StoreAssignmentRepository $storeRepository,
no va

2022-10-11 12:43 UTC, agustinfranc commented on app/Http/Controllers/AssignmentController.php
> +    public function show($id)
no va

2022-10-11 12:45 UTC, agustinfranc requested changes

2022-10-11 12:45 UTC, agustinfranc commented on app/Repositories/Companion/GetCompanionRepository.php
> +    public static function show($id)
seguir nomenclatura existente en el archivo, si el anterior se llama getAll entoces este sera getOne

2022-10-11 12:45 UTC, agustinfranc commented on app/Repositories/Client/GetClientRepository.php
> +    public static function show($id)
seguir nomenclatura existente en el archivo, si el anterior se llama getAll entoces este sera getOne

2022-10-11 12:47 UTC, agustinfranc requested changes
cambiar nombre pr ya que va a ser el nombre del commit que entre a develop. quitar assignment

2022-10-11 13:23 UTC, agustinfranc commented on app/Http/Controllers/AssignmentController.php
> +        private readonly StoreAssignmentRepository $storeRepository,
```suggestion
        private readonly StoreAssignmentRepository $storeRepository
```

2022-10-11 13:24 UTC, agustinfranc commented on app/Http/Controllers/AssignmentController.php
>  use App\Repositories\Assignment\StoreAssignmentRepository;
```suggestion
use App\Repositories\Assignment\StoreAssignmentRepository;
use Illuminate\Http\Request;
```

2022-10-11 13:26 UTC, agustinfranc approved these changes

2022-10-11 13:26 UTC, merged